### ISSUE TITLE
Support MQTT5

### ISSUE THREAD

**Issue by vincentdephily** [00imvj00/mqttrs#16]
This'll be a lot of work, but I'm putting it out there as a goal for 0.3 or later. I'll hopefully start working on this next year.

Hopefully we can keep the API stateless (not requiring a protocol argument).

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html
https://www.hivemq.com/blog/mqtt-5-foundational-changes-in-the-protocol/

**Comment by 00imvj00** [comment]
@vincentdephily @MathiasKoch do you guys think we should maybe provide support for 5.0 now that it is stable? 

if we don't have any other priorities, we can start working on this, may be?

**Comment by vincentdephily** [comment]
Sure. I won't be actually using MQTT5 for a while, but I'll be happy to help with design or review.

API-wise, it'd be great if we could keep it version-agnostic: the same mqttrs-using codebase would be able to talk to either an MQTT3 or MQTT5 host. For example we could implement extended packet properties for both protocol versions but it'd just be an empty list for MQTT3. Not sure if we can play that game for all the 3-vs-5 differences. Then there's the issue of statelessness: can we distinguish an MQTT5 publish from an MQTT3 publish when reading the bytes, or do we need to tell the decoder what to expect ? Maybe the best thing to to is to have a separate set of structs for MQTT3 and MQTT5, but let them both implement the same trait ?

Ok, I'm just speculating wildly at this point :laughing:,  I better let you look properly at the specs/code and come up with something.

**Comment by 00imvj00** [comment]
Yes, I will study the specs and will come up with plan or may be reference implementation and then we can iterate on that.

**Comment by MathiasKoch** [comment]
To be honest i have not even started looking into using MQTT5. I think most of the cloud providers still doesn't offer it, so it wouldn't be interesting for me personally.
That said i think being ahead of demand is never a bad thing.

Personally for me i would be more interested in seeing an alloc-free version of this crate (alloc feature flag). But i think it's a bit hard with the current implementation, based on `Bytes`, as that is inherently a heap based crate. Any suggestions on a way to make this heapless, that would work for you guys? Than i can try to open an issue, and investigate that option in practice?

**Comment by 00imvj00** [comment]
If we want to make it heap free, in that case, we might want to take `Read`, `Write` traits as param for decode instead of `Bytes`, this is something I always had in mind. If we can make `encode`, `decode` methods trait-based then I think we might be able to achieve that.

There is another way, where instead of storing the actual values, we just store references, but for that also we might want to have at least one allocation. This approach seems very promising, according to me.

I would love to know if you guys have any more ideas.

**Comment by 00imvj00** [comment]
@vincentdephily I have started reading on mqtt5 doc. i will create aggrgated doc for this.

**Comment by 00imvj00** [comment]
After reading the specs, I realized how detailed mqtt5 is. it is pretty amazing to see how many use-cases it covers. I feel at this point, we should experiment with v5 separately. once we have fair understanding and feel ok, then only we should try to merge both. 

In my opinion, keeping them separate would be a better choice.

closing this, as might not be useful anymore. reopen if more discussion on this is required.

**Comment by ajsb85** [comment]
Branch to follow the progress

https://github.com/00imvj00/mqttrs/tree/mqtt5_support
