### ISSUE TITLE
Proper way to extract packet length?

### ISSUE THREAD

**Issue by mjaakkol** [00imvj00/mqttrs#35]
With the new API *decode_slice* it is a bit unclear what's the best way to the extract packet length?

I guess I could use *read_header* but then it is called as duplicate inside *decode_slice* as well.

I generally I shouldn't really need it but if there are multiple packets send with Qos 0, I might end up having more than one packet waiting in my receive queue below socket-layers.  In this case, I need to know where packet starts and ends. Adding traditional length: &mut usize into *decode_slice* (1+remaining length) would work but wanted to understand if there is already some more clever way that I've missed.

**Comment by 00imvj00** [comment]
@mjaakkol thank you for pointing out the confusion in the lib. We are working on polishing the  api so, it is easy to understand and perform according to the expectations. I will keep your suggestion in mind. :)

**Comment by phil-opp** [comment]
Any news about this?
