### ISSUE TITLE
Purging 0.4.0 in favour of simplicity and little bit of performance cost.

### ISSUE THREAD

**Issue by 00imvj00** [00imvj00/mqttrs#39]
We tried to implement single allocation encoding and decoding, which is added in `0.4.0`, but it made things bit complicated.

Also it introduced lots of lifetime references, which makes adding this lib in async code very complicated.

So, this PR is just a discussion in order to bring back `0.3.0` as version bump to 0.5.0 and then stabilize to 1.0 in near future.

@vincentdephily @MathiasKoch need your guide in this.

**Comment by 00imvj00** [comment]
@MathiasKoch @vincentdephily ^^

**Comment by MathiasKoch** [comment]
I would be sad to see that go, as it is the only "feature" keeping me here. I need the no-alloc for my application. That said, i can always just fork. In an idea world, i would just lie to see less fragmentation of ecosystem, not more.

I am also not in a position currently where i have time to look into solving the painpoints, especially as i have still not been presented with the actual pain points, more than "it's a lifetime thing"

**Comment by 00imvj00** [comment]
Is there any other way we can resolve this then ? where we can do `no-alloc` without lifetimes?

**Comment by 00imvj00** [comment]
@MathiasKoch can we use Pin instead of taking lifetime??

**Comment by MathiasKoch** [comment]
My familiarity with Pin is very limited, but i think the issue might be the inner type of said pin? String is not an option, and i don't think Pin<&str> removes the need for the lifetime?

**Comment by 00imvj00** [comment]
Yeah, true. I tried that. Doesn't work. by the way, are you using this in prod? if yes, can i know what kind of prod environment this is being used?

**Comment by MathiasKoch** [comment]
Yeah, we are using it in prod ;) 

It's an IIoT device based on STM32, sending data to AWS, with roughly a stack of
- https://github.com/BlackbirdHQ/ublox-cellular-rs
- https://github.com/BlackbirdHQ/mqttrust
- https://github.com/BlackbirdHQ/rustot

Most of it is still work in progress, while the lower level stuff is starting to settle in.

**Comment by 00imvj00** [comment]
awesome. 👍🏽

**Comment by MathiasKoch** [comment]
It could be worth looking into how smoltcp handles their lifetimes using the managed crate.
They have extensive async support, allows alloc free nostd usage, and is also widely used in full-blown std applications.

**Comment by 00imvj00** [comment]
Interesting. Sure I will check it out.
