### ISSUE TITLE
QoS::AtMostOnce not handled properly when encoding/decoding a publish packet

### ISSUE THREAD

**Issue by vincentdephily** [00imvj00/mqttrs#6]
Mqttrs always expects a `PacketIdentifier` to be present, but the spec explains that the field is [only present in PUBLISH Packets where the QoS level is 1 or 2](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718039).

The symptoms are missing two initial bytes of payload when decoding an AtMostOnce publish packet, a panic when trying to encode a publish packet with `pid=None`, corrupted payload when read by conforming clients, etc.

I'll try to send a PR.

**Comment by 00imvj00** [comment]
awesome, thank you.

**Comment by vincentdephily** [comment]
Thanks for the fix, sorry for never following up with a PR: priorities shifted and holidays happened. I'll get back to QoS soon and hopefully stress-test this.

**Comment by 00imvj00** [comment]
It is ok. :) and thank you for finding issues.

**Comment by vincentdephily** [comment]
Sorry, not sure how I missed that, but only `from_buffer()` was fixed, leaving `to_buffer()` with the same bug. It should be possible to encode a `Publish` packet without a `PacketIdentifier`, if the QoS is 0.

**Comment by vincentdephily** [comment]
I've got the fix, just working on a more comprehensive test.
